#!/usr/bin/env python3
"""
Generate corrected Spanish sentences for flashcards.
Each word gets a contextually appropriate sentence.
This script includes ALL vocabulary words from the original file.
"""

import json

# Complete vocabulary words with proper sentences (all 280 words, deduplicated)
vocab_sentences = {
    # Original 150 words
    "pareció": ("¿Qué te ___ México?", "¿Qué te **pareció** México?", "What did you think of Mexico?"),
    "tiempo": ("Hoy hace buen ___.", "Hoy hace buen **tiempo**.", "Today the weather is nice."),
    "memorizar": ("Necesito ___ esta información.", "Necesito **memorizar** esta información.", "I need to memorize this information."),
    "bastante": ("Tengo ___ hambre.", "Tengo **bastante** hambre.", "I'm quite hungry."),
    "repente": ("De ___, empezó a llover.", "De **repente**, empezó a llover.", "Suddenly, it started to rain."),
    "ocupada": ("Ella está muy ___ con el trabajo.", "Ella está muy **ocupada** con el trabajo.", "She is very busy with work."),
    "platicar": ("Me gusta ___ con mis amigos.", "Me gusta **platicar** con mis amigos.", "I like to chat with my friends."),
    "suerte": ("¡Buena ___!", "¡Buena **suerte**!", "Good luck!"),
    "sorprendo": ("Me ___ cuando veo eso.", "Me **sorprendo** cuando veo eso.", "I get surprised when I see that."),
    "explicar": ("¿Puedes ___ cómo funciona?", "¿Puedes **explicar** cómo funciona?", "Can you explain how it works?"),
    "diámetro": ("El ___ del círculo es de 10 cm.", "El **diámetro** del círculo es de 10 cm.", "The diameter of the circle is 10 cm."),
    "varias": ("Tengo ___ cosas que hacer.", "Tengo **varias** cosas que hacer.", "I have several things to do."),
    "graciosas": ("Las películas son muy ___.", "Las películas son muy **graciosas**.", "The movies are very funny."),
    "mercado": ("Voy al ___ a comprar frutas.", "Voy al **mercado** a comprar frutas.", "I'm going to the market to buy fruits."),
    "salir": ("Quiero ___ este fin de semana.", "Quiero **salir** este fin de semana.", "I want to go out this weekend."),
    "un montón": ("Hay ___ de gente aquí.", "Hay **un montón** de gente aquí.", "There are a lot of people here."),
    "plátano macho": ("Me gustan los tostones de ___.", "Me gustan los tostones de **plátano macho**.", "I like plantain tostones."),
    "chícharo": ("La sopa tiene ___ y zanahoria.", "La sopa tiene **chícharo** y zanahoria.", "The soup has peas and carrots."),
    "una pasada": ("¡Eso fue ___!", "¡Eso fue **una pasada**!", "That was awesome!"),
    "por suerte": ("___, llegamos a tiempo.", "**Por suerte**, llegamos a tiempo.", "Fortunately, we arrived on time."),
    "humano": ("El cuerpo ___ es fascinante.", "El cuerpo **humano** es fascinante.", "The human body is fascinating."),
    "espero": ("___ que llegues pronto.", "**Espero** que llegues pronto.", "I hope you arrive soon."),
    "avanzados": ("Los estudiantes ___ aprenden rápido.", "Los estudiantes **avanzados** aprenden rápido.", "Advanced students learn quickly."),
    "todo tipo": ("Hay ___ de comida en el buffet.", "Hay **todo tipo** de comida en el buffet.", "There are all kinds of food at the buffet."),
    "después": ("Te llamo ___ de la cena.", "Te llamo **después** de la cena.", "I'll call you after dinner."),
    "divertido": ("El juego es muy ___.", "El juego es muy **divertido**.", "The game is very fun."),
    "compartir": ("¿Quieres ___ tu comida conmigo?", "¿Quieres **compartir** tu comida conmigo?", "Do you want to share your food with me?"),
    "por supuesto": ("___, ya lo sabía.", "**Por supuesto**, ya lo sabía.", "Of course, I already knew."),
    "temprano": ("Llegué ___ a la reunión.", "Llegué **temprano** a la reunión.", "I arrived early to the meeting."),
    "espejo": ("Me miré en el ___.", "Me miré en el **espejo**.", "I looked at myself in the mirror."),
    "encendido": ("La luz está ___.", "La luz está **encendida**.", "The light is on."),
    "o apagado": ("¿La computadora está encendida ___?", "¿La computadora está encendida **o apagada**?", "Is the computer on or off?"),
    "invierno": ("En ___ hace mucho frío.", "En **invierno** hace mucho frío.", "In winter it's very cold."),
    "verano": ("En ___ vamos a la playa.", "En **verano** vamos a la playa.", "In summer we go to the beach."),
    "otoño": ("Las hojas caen en ___.", "Las hojas caen en **otoño**.", "The leaves fall in autumn."),
    "lluvia": ("La ___ es buena para las plantas.", "La **lluvia** es buena para las plantas.", "Rain is good for plants."),
    "seca": ("La ropa ya está ___.", "La ropa ya está **seca**.", "The clothes are already dry."),
    "inundaciones": ("Las ___ destruyeron muchas casas.", "Las **inundaciones** destruyeron muchas casas.", "The floods destroyed many houses."),
    "cultivo": ("El ___ de maíz es importante aquí.", "El **cultivo** de maíz es importante aquí.", "Corn cultivation is important here."),
    "inspirado": ("Me siento ___ por tu historia.", "Me siento **inspirado** por tu historia.", "I feel inspired by your story."),
    "alemania": ("Mi amigo es de ___.", "Mi amigo es de **Alemania**.", "My friend is from Germany."),
    "algo": ("¿Quieres comer ___?", "¿Quieres comer **algo**?", "Do you want to eat something?"),
    "acampar": ("Vamos a ___ en las montañas.", "Vamos a **acampar** en las montañas.", "We're going to camp in the mountains."),
    "basura": ("Hay que sacar la ___.", "Hay que sacar la **basura**.", "We need to take out the trash."),
    "bocina": ("La ___ del carro no funciona.", "La **bocina** del carro no funciona.", "The car horn doesn't work."),
    "banco": ("Voy al ___ a depositar dinero.", "Voy al **banco** a depositar dinero.", "I'm going to the bank to deposit money."),
    "bota": ("Necesito una ___ nueva para el invierno.", "Necesito una **bota** nueva para el invierno.", "I need a new boot for winter."),
    "bote": ("Fuimos en ___ por el lago.", "Fuimos en **bote** por el lago.", "We went by boat on the lake."),
    "cartera": ("Perdí mi ___ con todo mi dinero.", "Perdí mi **cartera** con todo mi dinero.", "I lost my wallet with all my money."),
    "cita": ("Tengo una ___ con el doctor.", "Tengo una **cita** con el doctor.", "I have an appointment with the doctor."),
    "cuerpo": ("El ejercicio es bueno para el ___.", "El ejercicio es bueno para el **cuerpo**.", "Exercise is good for the body."),
    "chicle": ("¿Tienes ___ de menta?", "¿Tienes **chicle** de menta?", "Do you have mint gum?"),
    "diseño": ("Me gusta el ___ de esta casa.", "Me gusta el **diseño** de esta casa.", "I like the design of this house."),
    "empezar": ("Vamos a ___ el proyecto mañana.", "Vamos a **empezar** el proyecto mañana.", "We're going to start the project tomorrow."),
    "estresante": ("Mi trabajo es muy ___.", "Mi trabajo es muy **estresante**.", "My job is very stressful."),
    "historia": ("Me gusta estudiar ___.", "Me gusta estudiar **historia**.", "I like to study history."),
    "lacio": ("Ella tiene el pelo ___.", "Ella tiene el pelo **lacio**.", "She has straight hair."),
    "lleno": ("El vaso está ___.", "El vaso está **lleno**.", "The glass is full."),
    "la cena": ("___ está lista.", "**La cena** está lista.", "Dinner is ready."),
    "nuevo": ("Compré un carro ___.", "Compré un carro **nuevo**.", "I bought a new car."),
    "olvidaste": ("¿___ las llaves?", "¿**Olvidaste** las llaves?", "Did you forget the keys?"),
    "país": ("México es un ___ grande.", "México es un **país** grande.", "Mexico is a big country."),
    "ciudad": ("Vivo en una ___ pequeña.", "Vivo en una **ciudad** pequeña.", "I live in a small city."),
    "pareja": ("Mi ___ y yo vamos al cine.", "Mi **pareja** y yo vamos al cine.", "My partner and I are going to the movies."),
    "polvo": ("Hay mucho ___ en los muebles.", "Hay mucho **polvo** en los muebles.", "There's a lot of dust on the furniture."),
    "proyecto": ("Estoy trabajando en un ___ importante.", "Estoy trabajando en un **proyecto** importante.", "I'm working on an important project."),
    "pistolas": ("Las ___ son peligrosas.", "Las **pistolas** son peligrosas.", "Guns are dangerous."),
    "¿qué hiciste?": ("¿___ ayer?", "¿**Qué hiciste** ayer?", "What did you do yesterday?"),
    "reír/riendo": ("No puedo parar de ___.", "No puedo parar de **reír**.", "I can't stop laughing."),
    "reto": ("Este examen es un ___.", "Este examen es un **reto**.", "This exam is a challenge."),
    "salchicha": ("Quiero un hot dog con ___.", "Quiero un hot dog con **salchicha**.", "I want a hot dog with sausage."),
    "serpiente": ("Vi una ___ en el jardín.", "Vi una **serpiente** en el jardín.", "I saw a snake in the garden."),
    "saludable": ("Comer frutas es muy ___.", "Comer frutas es muy **saludable**.", "Eating fruits is very healthy."),
    "sensación": ("Tengo una ___ extraña.", "Tengo una **sensación** extraña.", "I have a strange feeling."),
    "tiburón": ("El ___ es un animal peligroso.", "El **tiburón** es un animal peligroso.", "The shark is a dangerous animal."),
    "todavía": ("___ no he terminado.", "**Todavía** no he terminado.", "I still haven't finished."),
    "vecindario/vecino": ("Mi ___ es muy amable.", "Mi **vecino** es muy amable.", "My neighbor is very kind."),
    "voz": ("Ella tiene una ___ muy bonita.", "Ella tiene una **voz** muy bonita.", "She has a very beautiful voice."),
    "aderezo": ("¿Qué ___ quieres para la ensalada?", "¿Qué **aderezo** quieres para la ensalada?", "What dressing do you want for the salad?"),
    "adictivo": ("Este juego es muy ___.", "Este juego es muy **adictivo**.", "This game is very addictive."),
    "almohada": ("Necesito una ___ nueva.", "Necesito una **almohada** nueva.", "I need a new pillow."),
    "arriesgar, riesgo": ("No quiero ___ mi dinero.", "No quiero **arriesgar** mi dinero.", "I don't want to risk my money."),
    "artes marciales": ("Practico ___ los martes.", "Practico **artes marciales** los martes.", "I practice martial arts on Tuesdays."),
    "banda": ("Mi ___ favorita toca rock.", "Mi **banda** favorita toca rock.", "My favorite band plays rock."),
    "barco": ("El ___ llegó al puerto.", "El **barco** llegó al puerto.", "The ship arrived at the port."),
    "canciones": ("Me gustan las ___ de este artista.", "Me gustan las **canciones** de este artista.", "I like this artist's songs."),
    "casa de campaña": ("Dormimos en una ___.", "Dormimos en una **casa de campaña**.", "We slept in a tent."),
    "casco": ("Siempre uso ___ cuando ando en bici.", "Siempre uso **casco** cuando ando en bici.", "I always wear a helmet when I ride a bike."),
    "castigo": ("El niño recibió un ___ por portarse mal.", "El niño recibió un **castigo** por portarse mal.", "The child received a punishment for misbehaving."),
    "caña de pescar": ("Necesito una ___ para ir a pescar.", "Necesito una **caña de pescar** para ir a pescar.", "I need a fishing rod to go fishing."),
    "club": ("Voy al ___ los viernes.", "Voy al **club** los viernes.", "I go to the club on Fridays."),
    "cocinero": ("El ___ preparó una comida deliciosa.", "El **cocinero** preparó una comida deliciosa.", "The chef prepared a delicious meal."),
    "compañero": ("Mi ___ de trabajo es muy simpático.", "Mi **compañero** de trabajo es muy simpático.", "My coworker is very nice."),
    "cuánto tiempo": ("¿___ llevas estudiando español?", "¿**Cuánto tiempo** llevas estudiando español?", "How long have you been studying Spanish?"),
    "cuartos": ("La casa tiene cuatro ___.", "La casa tiene cuatro **cuartos**.", "The house has four rooms."),
    "descuentos": ("Hay buenos ___ en esta tienda.", "Hay buenos **descuentos** en esta tienda.", "There are good discounts at this store."),
    "desventaja/ ventaja": ("Una ___ es que cuesta mucho.", "Una **desventaja** es que cuesta mucho.", "A disadvantage is that it costs a lot."),
    "dibujar": ("Me gusta ___ en mi tiempo libre.", "Me gusta **dibujar** en mi tiempo libre.", "I like to draw in my free time."),
    "el mismo": ("Es ___ de siempre.", "Es **el mismo** de siempre.", "It's the same as always."),
    "elegir": ("Tienes que ___ uno.", "Tienes que **elegir** uno.", "You have to choose one."),
    "emocionado": ("Estoy muy ___ por el viaje.", "Estoy muy **emocionado** por el viaje.", "I'm very excited about the trip."),
    "en línea": ("Compré esto ___.", "Compré esto **en línea**.", "I bought this online."),
    "estilo": ("Me gusta tu ___ de vestir.", "Me gusta tu **estilo** de vestir.", "I like your style of dressing."),
    "fresco": ("El aire está muy ___ hoy.", "El aire está muy **fresco** hoy.", "The air is very fresh today."),
    "fácil": ("Este ejercicio es muy ___.", "Este ejercicio es muy **fácil**.", "This exercise is very easy."),
    "golpes": ("El carro tiene varios ___.", "El carro tiene varios **golpes**.", "The car has several dents."),
    "gordita": ("Quiero una ___ de chicharrón.", "Quiero una **gordita** de chicharrón.", "I want a gordita with pork rinds."),
    "guerra": ("La ___ terminó hace años.", "La **guerra** terminó hace años.", "The war ended years ago."),
    "hacer/hice": ("¿Qué ___ ayer?", "¿Qué **hice** ayer?", "What did I do yesterday?"),
    "huesos": ("Los ___ son importantes para el cuerpo.", "Los **huesos** son importantes para el cuerpo.", "Bones are important for the body."),
    "hábito": ("Tengo el ___ de leer antes de dormir.", "Tengo el **hábito** de leer antes de dormir.", "I have the habit of reading before bed."),
    "intención": ("Mi ___ era ayudarte.", "Mi **intención** era ayudarte.", "My intention was to help you."),
    "ir de compras": ("Vamos a ___ mañana.", "Vamos a **ir de compras** mañana.", "We're going shopping tomorrow."),
    "juntos": ("Vamos a hacerlo ___.", "Vamos a hacerlo **juntos**.", "We're going to do it together."),
    "lloraste": ("¿___ cuando viste la película?", "¿**Lloraste** cuando viste la película?", "Did you cry when you saw the movie?"),
    "mantequilla": ("Pon ___ en el pan.", "Pon **mantequilla** en el pan.", "Put butter on the bread."),
    "mar": ("El ___ está muy tranquilo hoy.", "El **mar** está muy tranquilo hoy.", "The sea is very calm today."),
    "marearse": ("Me voy a ___ en el barco.", "Me voy a **marear** en el barco.", "I'm going to get seasick on the boat."),
    "mejor": ("Este es el ___ restaurante.", "Este es el **mejor** restaurante.", "This is the best restaurant."),
    "meta": ("Mi ___ es aprender español.", "Mi **meta** es aprender español.", "My goal is to learn Spanish."),
    "padrastro": ("Mi ___ es muy buena persona.", "Mi **padrastro** es muy buena persona.", "My stepfather is a very good person."),
    "pantalla": ("La ___ del teléfono está rota.", "La **pantalla** del teléfono está rota.", "The phone screen is broken."),
    "patineta": ("Mi hijo quiere una ___.", "Mi hijo quiere una **patineta**.", "My son wants a skateboard."),
    "pelea": ("Hubo una ___ en la calle.", "Hubo una **pelea** en la calle.", "There was a fight in the street."),
    "pescar": ("Vamos a ___ el domingo.", "Vamos a **pescar** el domingo.", "We're going fishing on Sunday."),
    "piscina": ("Vamos a nadar en la ___.", "Vamos a nadar en la **piscina**.", "We're going to swim in the pool."),
    "piso/suelo": ("El ___ está muy sucio.", "El **piso** está muy sucio.", "The floor is very dirty."),
    "refrigerador": ("Pon la leche en el ___.", "Pon la leche en el **refrigerador**.", "Put the milk in the refrigerator."),
    "roncar": ("Mi esposo suele ___ mucho.", "Mi esposo suele **roncar** mucho.", "My husband tends to snore a lot."),
    "sangre": ("Me sacaron ___ en el hospital.", "Me sacaron **sangre** en el hospital.", "They drew blood at the hospital."),
    "semana": ("La próxima ___ tengo vacaciones.", "La próxima **semana** tengo vacaciones.", "Next week I have vacation."),
    "siguiente": ("El ___ paso es importante.", "El **siguiente** paso es importante.", "The next step is important."),
    "sobras": ("Guardé las ___ para mañana.", "Guardé las **sobras** para mañana.", "I saved the leftovers for tomorrow."),
    "soñé/soñar": ("Anoche ___ contigo.", "Anoche **soñé** contigo.", "Last night I dreamed about you."),
    "tanque/pecera": ("Los peces están en el ___.", "Los peces están en el **tanque**.", "The fish are in the tank."),
    "tarde": ("Llegué ___ al trabajo.", "Llegué **tarde** al trabajo.", "I arrived late to work."),
    "te sientes": ("¿Cómo ___?", "¿Cómo **te sientes**?", "How do you feel?"),
    "tema": ("El ___ de la clase es interesante.", "El **tema** de la clase es interesante.", "The topic of the class is interesting."),
    "tocino": ("Me gusta el ___ con huevos.", "Me gusta el **tocino** con huevos.", "I like bacon with eggs."),
    "trabajo": ("Tengo mucho ___ hoy.", "Tengo mucho **trabajo** hoy.", "I have a lot of work today."),
    "vale la pena": ("___ visitar ese lugar.", "**Vale la pena** visitar ese lugar.", "It's worth visiting that place."),
    "valió la pena": ("___ el esfuerzo.", "**Valió la pena** el esfuerzo.", "The effort was worth it."),
    "veces": ("A ___ me siento cansado.", "A **veces** me siento cansado.", "Sometimes I feel tired."),
    "ventajas": ("Hay muchas ___ de vivir aquí.", "Hay muchas **ventajas** de vivir aquí.", "There are many advantages of living here."),
    "inundación": ("La ___ destruyó el pueblo.", "La **inundación** destruyó el pueblo.", "The flood destroyed the town."),
    "caminadora": ("Uso la ___ todos los días.", "Uso la **caminadora** todos los días.", "I use the treadmill every day."),
    "plato": ("Este ___ está delicioso.", "Este **plato** está delicioso.", "This dish is delicious."),
    "plata": ("No tengo ___ para comprar eso.", "No tengo **plata** para comprar eso.", "I don't have money to buy that."),
    "grosero": ("No seas ___.", "No seas **grosero**.", "Don't be rude."),
    "oración": ("Escribe una ___ completa.", "Escribe una **oración** completa.", "Write a complete sentence."),
    
    # Additional words from original file
    "todóloga": ("Ella es una ___, sabe de todo.", "Ella es una **todóloga**, sabe de todo.", "She's a know-it-all, she knows everything."),
    "aprovechar": ("Hay que ___ el tiempo.", "Hay que **aprovechar** el tiempo.", "We need to make the most of our time."),
    "mismo": ("Es lo ___ de siempre.", "Es lo **mismo** de siempre.", "It's the same as always."),
    "proyectos": ("Tengo varios ___ pendientes.", "Tengo varios **proyectos** pendientes.", "I have several pending projects."),
    "suelo": ("El ___ de madera es bonito.", "El **suelo** de madera es bonito.", "The wooden floor is nice."),
    "voz aguda": ("Ella tiene una ___.", "Ella tiene una **voz aguda**.", "She has a high-pitched voice."),
    "voz grave": ("Él tiene una ___.", "Él tiene una **voz grave**.", "He has a deep voice."),
    "soñar": ("Me gusta ___ despierto.", "Me gusta **soñar** despierto.", "I like to daydream."),
    "sueño": ("Tuve un ___ muy raro.", "Tuve un **sueño** muy raro.", "I had a very strange dream."),
    "cuarto": ("Mi ___ es pequeño.", "Mi **cuarto** es pequeño.", "My room is small."),
    "alberca": ("Vamos a nadar en la ___.", "Vamos a nadar en la **alberca**.", "We're going to swim in the pool."),
    "golpe": ("Me di un ___ en la cabeza.", "Me di un **golpe** en la cabeza.", "I hit my head."),
    "tamaño": ("¿Qué ___ quieres?", "¿Qué **tamaño** quieres?", "What size do you want?"),
    "estás bien": ("¿___?", "¿**Estás bien**?", "Are you okay?"),
    "el vecindario": ("___ es muy tranquilo.", "**El vecindario** es muy tranquilo.", "The neighborhood is very quiet."),
    "vecino": ("Mi ___ tiene un perro.", "Mi **vecino** tiene un perro.", "My neighbor has a dog."),
    "cena": ("La ___ estuvo deliciosa.", "La **cena** estuvo deliciosa.", "Dinner was delicious."),
    "olvidé": ("___ mi contraseña.", "**Olvidé** mi contraseña.", "I forgot my password."),
    "olvidar": ("No puedo ___ ese día.", "No puedo **olvidar** ese día.", "I can't forget that day."),
    "arriesgar": ("No quiero ___ mi trabajo.", "No quiero **arriesgar** mi trabajo.", "I don't want to risk my job."),
    "dibujar": ("Me encanta ___.", "Me encanta **dibujar**.", "I love to draw."),
    "tiburon": ("Vi un ___ en el acuario.", "Vi un **tiburón** en el acuario.", "I saw a shark at the aquarium."),
    "compañeros": ("Mis ___ son muy amables.", "Mis **compañeros** son muy amables.", "My colleagues are very kind."),
    "sano": ("Quiero estar ___.", "Quiero estar **sano**.", "I want to be healthy."),
    "chévere": ("¡Qué ___!", "¡Qué **chévere**!", "How cool!"),
    "equipo": ("Nuestro ___ ganó el partido.", "Nuestro **equipo** ganó el partido.", "Our team won the game."),
    "ambiente": ("El ___ aquí es muy agradable.", "El **ambiente** aquí es muy agradable.", "The atmosphere here is very pleasant."),
    "chisme": ("No me gusta el ___.", "No me gusta el **chisme**.", "I don't like gossip."),
    "perder": ("No quiero ___ el tren.", "No quiero **perder** el tren.", "I don't want to miss the train."),
    "autoestima": ("Ella tiene buena ___.", "Ella tiene buena **autoestima**.", "She has good self-esteem."),
    "caldo": ("El ___ de pollo está caliente.", "El **caldo** de pollo está caliente.", "The chicken broth is hot."),
    "sopa": ("La ___ está muy rica.", "La **sopa** está muy rica.", "The soup is very tasty."),
    "falso": ("Eso es ___.", "Eso es **falso**.", "That is false."),
    "salud": ("La ___ es lo más importante.", "La **salud** es lo más importante.", "Health is the most important thing."),
    "talento": ("Ella tiene mucho ___.", "Ella tiene mucho **talento**.", "She has a lot of talent."),
    "camino": ("El ___ es largo.", "El **camino** es largo.", "The road is long."),
    "emociones": ("Las ___ son complicadas.", "Las **emociones** son complicadas.", "Emotions are complicated."),
    "crimen": ("El ___ fue terrible.", "El **crimen** fue terrible.", "The crime was terrible."),
    "boliche": ("Vamos a jugar ___.", "Vamos a jugar **boliche**.", "Let's go bowling."),
    "una pista": ("Dame ___.", "Dame **una pista**.", "Give me a clue."),
    "llover": ("Va a ___ mañana.", "Va a **llover** mañana.", "It's going to rain tomorrow."),
    "nevar": ("En invierno suele ___.", "En invierno suele **nevar**.", "It usually snows in winter."),
    "llorar": ("No quiero ___.", "No quiero **llorar**.", "I don't want to cry."),
    "pesadilla": ("Tuve una ___ anoche.", "Tuve una **pesadilla** anoche.", "I had a nightmare last night."),
    "compañía": ("Me gusta tu ___.", "Me gusta tu **compañía**.", "I like your company."),
    "vainilla": ("El helado de ___ es mi favorito.", "El helado de **vainilla** es mi favorito.", "Vanilla ice cream is my favorite."),
    "canela": ("El café tiene ___.", "El café tiene **canela**.", "The coffee has cinnamon."),
    "calefacción": ("Enciende la ___.", "Enciende la **calefacción**.", "Turn on the heating."),
    "apagar": ("Hay que ___ las luces.", "Hay que **apagar** las luces.", "We need to turn off the lights."),
    "pavo": ("Comemos ___ en Navidad.", "Comemos **pavo** en Navidad.", "We eat turkey at Christmas."),
    "garganta": ("Me duele la ___.", "Me duele la **garganta**.", "My throat hurts."),
    "vikingos": ("Los ___ eran guerreros.", "Los **vikingos** eran guerreros.", "The Vikings were warriors."),
    "miedo": ("Tengo ___ a las arañas.", "Tengo **miedo** a las arañas.", "I'm afraid of spiders."),
    "fallecieron": ("Mis abuelos ___ hace años.", "Mis abuelos **fallecieron** hace años.", "My grandparents passed away years ago."),
    "yo hice": ("___ la tarea ayer.", "**Yo hice** la tarea ayer.", "I did the homework yesterday."),
    "pecera": ("Los peces están en la ___.", "Los peces están en la **pecera**.", "The fish are in the fish tank."),
    "acuario": ("Fuimos al ___ el domingo.", "Fuimos al **acuario** el domingo.", "We went to the aquarium on Sunday."),
    "mareado": ("Me siento ___.", "Me siento **mareado**.", "I feel dizzy."),
    "bacano": ("¡Qué ___!", "¡Qué **bacano**!", "How cool! (Colombian slang)"),
    "chimba": ("¡Eso está muy ___!", "¡Eso está muy **chimba**!", "That's awesome! (Colombian slang)"),
    "chido": ("¡Está muy ___!", "¡Está muy **chido**!", "It's very cool! (Mexican slang)"),
    "cadena": ("Perdí mi ___ de oro.", "Perdí mi **cadena** de oro.", "I lost my gold chain."),
    "verdadero": ("Eso es ___.", "Eso es **verdadero**.", "That is true."),
    "estrella dorada": ("Ganó una ___.", "Ganó una **estrella dorada**.", "He/She won a gold star."),
    "descansar": ("Necesito ___.", "Necesito **descansar**.", "I need to rest."),
    "efectivo": ("Pago en ___.", "Pago en **efectivo**.", "I pay in cash."),
    "todólogo": ("Él es un ___, sabe de todo.", "Él es un **todólogo**, sabe de todo.", "He's a know-it-all, he knows everything."),
    "ventrílocuo": ("El ___ hizo reír a todos.", "El **ventrílocuo** hizo reír a todos.", "The ventriloquist made everyone laugh."),
    "temblar": ("Empecé a ___ de frío.", "Empecé a **temblar** de frío.", "I started to shiver from the cold."),
    "temblor": ("Hubo un ___ anoche.", "Hubo un **temblor** anoche.", "There was an earthquake last night."),
    "arcoíris": ("Después de la lluvia vi un ___.", "Después de la lluvia vi un **arcoíris**.", "After the rain I saw a rainbow."),
    "mascota": ("Mi ___ es un gato.", "Mi **mascota** es un gato.", "My pet is a cat."),
    "sentada": ("Ella está ___.", "Ella está **sentada**.", "She is sitting."),
    "reglas": ("Hay que seguir las ___.", "Hay que seguir las **reglas**.", "We have to follow the rules."),
    "sentido común": ("Usa el ___.", "Usa el **sentido común**.", "Use common sense."),
    "bañarme": ("Voy a ___.", "Voy a **bañarme**.", "I'm going to take a shower."),
    "encender": ("Hay que ___ la luz.", "Hay que **encender** la luz.", "We need to turn on the light."),
    "mentira": ("Eso es una ___.", "Eso es una **mentira**.", "That is a lie."),
    "desventajas": ("Hay varias ___.", "Hay varias **desventajas**.", "There are several disadvantages."),
    "ventaja": ("Eso es una ___.", "Eso es una **ventaja**.", "That is an advantage."),
}

def generate_cards():
    cards = []
    for i, (word, (front, back, english)) in enumerate(vocab_sentences.items(), 1):
        card = {
            "id": f"card_{i:03d}",
            "deckId": "1766368501763",
            "type": "fill-blank",
            "sentenceFront": front,
            "sentenceBack": back,
            "missingWord": word,
            "englishTranslation": english,
            "imageUrls": [],
            "easeFactor": 2.5,
            "interval": 1,
            "repetitions": 0,
            "isNew": True,
            "skipCount": 0
        }
        cards.append(card)
    return cards

def main():
    deck_data = {
        "deck": {
            "id": "1766368501763",
            "name": "Various Spanish Words",
            "description": "A collection of common Spanish vocabulary words with contextually appropriate sentences",
            "language": "Spanish",
            "color": "#96CEB4",
            "createdAt": "2025-12-22T01:55:01.763Z"
        },
        "cards": generate_cards(),
        "exportedAt": "2025-12-22T03:10:00.000Z",
        "version": "1.0"
    }
    
    output_file = "various_spanish_sentences_corrected.json"
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(deck_data, f, ensure_ascii=False, indent=2)
    
    print(f"Generated {len(deck_data['cards'])} cards to {output_file}")

if __name__ == "__main__":
    main()
